// ----------------------------------------------------------------------------------
// Microsoft Developer & Platform Evangelism
// 
// Copyright (c) Microsoft Corporation. All rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
// ----------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectDemoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductModelCatalogDescription
    {
        public int ProductModelID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Manufacturer { get; set; }
        public string Copyright { get; set; }
        public string ProductURL { get; set; }
        public string WarrantyPeriod { get; set; }
        public string WarrantyDescription { get; set; }
        public string NoOfYears { get; set; }
        public string MaintenanceDescription { get; set; }
        public string Wheel { get; set; }
        public string Saddle { get; set; }
        public string Pedal { get; set; }
        public string BikeFrame { get; set; }
        public string Crankset { get; set; }
        public string PictureAngle { get; set; }
        public string PictureSize { get; set; }
        public string ProductPhotoID { get; set; }
        public string Material { get; set; }
        public string Color { get; set; }
        public string ProductLine { get; set; }
        public string Style { get; set; }
        public string RiderExperience { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
